var host = '22.5.229.34';//IP地址
var port = '18888';//端口号
var useTLS = false;
var cleansession = false;


var topicData = [
    {
        topic:'C/EBD/SURVIVALSCALE/KPI/ALL/ZX',
        data:{
            non_risk_financial_amount:'10367.2',//非担险理财金额
            non_risk_financial_week:'+7',//非担险理财---较上周
            non_risk_financial_month:'+727',//非担险理财金额---较月初
            non_risk_financial_year:'+1114',//非担险理财金额---较年初
            risk_financial_amount:'299.1',//担险理财金额
            risk_financial_week:'-16.6',//担险理财金额---较上周
            risk_financial_month:'-31.2',//担险理财金额---较月初
            risk_financial_year:'0',//担险理财金额---较年初
        }
    },
    {
        topic:'C/EBD/SURVIVALSCALE/TREND/ALL/ZX',
        data:{
            non_risk_month_data:[//非担险理财---最近一月
                {date:'4.28-5.4',value:390},
                {date:'5.5-5.11',value:105},
                {date:'5.12-5.18',value:284},
                {date:'5.19-5.25',value:425},
                {date:'5.26-6.2',value:110},
            ],
            non_risk_year_data:[//非担险理财---最近一年
                {date:6,value:251},
                {date:7,value:289},
                {date:8,value:250},
                {date:9,value:241},
                {date:10,value:251},
                {date:11,value:290},
                {date:12,value:255},
                {date:1,value:274},
                {date:2,value:298},
                {date:3,value:252},
                {date:4,value:272},
                {date:5,value:299},
            ],
            risk_month_data:[//担险理财---最近一月
                {date:'5.28-6.4',value:284},
                {date:'6.5-6.11',value:425},
                {date:'6.12-6.18',value:110},
                {date:'6.19-6.25',value:390},
                {date:'6.26-7.2',value:210},
            ],
            risk_year_data:[//担险理财---最近一年
                {date:8,value:255},
                {date:9,value:274},
                {date:10,value:298},
                {date:11,value:252},
                {date:12,value:272},
                {date:1,value:299},
                {date:2,value:251},
                {date:3,value:289},
                {date:4,value:250},
                {date:5,value:241},
                {date:6,value:251},
                {date:7,value:289},
            ],
        }
    },
    {
        topic:'C/EBD/SURVIVALSCALE/EACH_CHANNEL_NON_RISK/ALL/ZX',
        data:[
            {name:'零售',value:5237,comparison_week:'+25.4',comparison_month:'+196.2',comparison_year:'+199.9'},
            {name:'对私',value:699,comparison_week:'+27.7',comparison_month:'+162.1',comparison_year:'+136.8'},
            {name:'财私',value:3424,comparison_week:'+28.4',comparison_month:'+325.6',comparison_year:'+747.0'},
            {name:'同业',value:1005,comparison_week:'-73.6',comparison_month:'43.1',comparison_year:'33.2'},
            {name:'国际',value:0,comparison_week:'0',comparison_month:'0',comparison_year:'-2.4'},
        ]
    },
    {
        topic:'C/EBD/SURVIVALSCALE/EACH_CHANNEL_RISK/ALL/ZX',
        data:[
            {name:'零售',value:23.1,comparison_week:'-2.3',comparison_month:'-13.9',comparison_year:'-24.2'},
            {name:'对私',value:275.9,comparison_week:'-14.2',comparison_month:'-19.2',comparison_year:'-35.3'},
            {name:'财私',value:0,comparison_week:'0',comparison_month:'0',comparison_year:'0'},
            {name:'同业',value:0,comparison_week:'0',comparison_month:'0',comparison_year:'0'},
            {name:'国际',value:0,comparison_week:'0',comparison_month:'0',comparison_year:'0'},
        ]
    }
]